name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Generate package-lock.json
        run: npm i --package-lock-only
      
      - name: Install dependencies
        run: |
          npm ci || npm install
          npm ls
        
      - name: Build project
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: out
          retention-days: 1

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm i --package-lock-only
          npm ci || npm install
        
      - name: Run linting
        run: npm run lint:check

  deploy:
    needs: [build, lint]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: out
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: out
          branch: gh-pages
          clean: true
          commit-message: "Deploy: ${{ github.sha }}"

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Status
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "Visit: https://kuramentooo.github.io/portfolio"
